title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://GinMsu.github.io

logo: "/assets/Raven Nation.png"

color_scheme: dark

aux_links:
  Template Repository: "/assets/Raven Nation.png"
